### PR TITLE
Feature/sbml

### PR DESCRIPTION
**Pull request by kaiserls**
# Description

This merge requests will allow to
- evaluate sbml models at multiple time points
- select specific parameters for the inference by their id
- select specific species for the inference by their id

Fixes issue #71 

## Type of change

Please tick at least one of the options. Delete the other options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Reactivated the  tests for the sbml models and extended the shape tests

## Checklist For Contributor

- [x] My code follows the style guidelines of this project (I installed pre-commit)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote my changes in the changelog in the `[unreleased]` section
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

## Checklist For Maintainers

- [x] Continuous Integration (CI) is successfully running
- [ ] Do we want to release/tag a new version? [✔️ / ❌]
  - [ ] If yes, add a release to the changelog and set the new version in pyproject.toml. After the merge, tag the release!

### CODE REVIEW

**Review by shoepfl — CHANGES_REQUESTED** [review]
Looks good to me. I also like to state explicitly that the parameters are adressed by their ids, not names.

The forward_and_jacobian method also works for me.

However, inference is not working with the current setup on my machine. Can you test this also on your side? Then we can fix this before merging it back to main

**Comment by kaiserls** [comment]
You mean we should mention explicitly in the doc strings that we do not use the parameter names and they are not necessarily the same as the ids? Could you mark a code section next time, where you would like to have changes implemented?

**Comment by shoepfl** [comment]
Sorry, no i like it the way it is but inference is currently not working with this branch on my machine and I did not find out yet why. Thats also why I suggested that you test it on your machine so that we can exclude that the error comes from an relative hdf5 import on my machine

**Review by shoepfl — APPROVED** [review]
Looks good to me. Really nice that this allows to handle more than one species and time points at once.

**Pull request merged**
